In [2]:
import numpy as np

P=np.matrix([[0, 0, 1], [0, 1 ,0], [1, 0, 0]])
A=np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])

res = np.dot(A, P)
print(res)

aux=A[0][2]



[[4 1 3]
 [9 5 1]
 [5 6 2]]


In [28]:
import numpy as np

def matrizIdentidade(n):
  M=np.zeros((n,n))
  M1=M.tolist()
  for j in range (n):
      for m in range (n):
          if (m==j):
              M1[j][m]=1.
              M[j][m]=1.  
  
  return M1, M


def pivot(A, k, i): 
    
    
  matrizIdent = matrizIdentidade(3)[1]

  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )

  indexMax = np.argmax( colAbs )

  iChange = indexMax + i

  aux = np.copy( A[ k, : ] )
  aux2 = np.copy(matrizIdent[ k, : ])  

  matrizIdent[ k, : ] = np.copy( matrizIdent[ iChange, : ] )
  matrizIdent[ iChange, : ] = np.copy( aux2 )  
    
  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )
    
  print(matrizIdent)  
  matrizIdent=matrizIdent.tolist()

  return A, matrizIdent


def eliminacaoGaussiana( A, n ): 
  mult=[]
  arrIdent=[]
  for k in np.arange( 0, n ): 
      for i in np.arange( k + 1, n + 1 ):
          A, matrizIdent = pivot(A, k, i)
          arrIdent.append(matrizIdent)
          m = A[ i, k ] / A[ k, k ]
          mult.append(m)
          A[ i, k ] = 0
          for j in np.arange( k + 1, n + 1 ):
              A[ i, j ] -= m * A[ k, j ]

            
  print(arrIdent)          
  return A, mult, arrIdent




def notacaoLU(A, n):
    
    Ms = []
    As = np.array((n, n))
    
    L = np.array((n, n))
    U = np.array((n, n))
    
    if (np.linalg.det(A)!=0):
        
         
        M = matrizIdentidade(n)  
        
        U, m, arrIdent = eliminacaoGaussiana( np.copy(A), n-1 )
        
        M, x = matrizIdentidade(n)
        
        counter=0
        M=np.array(M)
        m=np.array(m)
        M1=np.copy(M)
        mult=np.copy(m)
        
        for j in range (n):
          for m in range (n):
              if (m<j):
                M1[j][m]=mult[counter]
                counter+=1
        
        size = len(arrIdent)
        arrIdent = np.array(arrIdent)
        arr_final = np.copy(arrIdent[0])
        
        for k in range (1, size):
            arr_final = np.dot(arr_final, arrIdent[k])
    
    print(arr_final)

    
    L=np.copy(M1)
    print('L = ')
    print(L)
    print('U = ')
    print(U)
    
    print(np.dot(arr_final, U))
    
    return L, U

  
def solucaoLU(b, L, U, n):
  y=np.array(n)
  x=np.array(n)
  y=(np.linalg.solve(L, b))
  x=(np.linalg.solve(U, y))
  return x
  


A = np.array([[3.,2.,4.],[1.,1.,2.],[4.,3.,2.]])
b = np.array([1.,2.,3.])
n = A.shape[0]

L, U = notacaoLU(A, n)
x = solucaoLU(b, L, U, n)
print ('x = ', x)


[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]]
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]]
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
[[[0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0]], [[0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0]], [[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0]]]
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
L = 
[[ 1.          0.          0.        ]
 [ 0.25        1.          0.        ]
 [ 1.33333333  0.75        1.        ]]
U = 
[[ 3.          2.          4.        ]
 [ 0.          0.33333333 -3.33333333]
 [ 0.          0.          4.        ]]
[[ 3.          2.          4.        ]
 [ 0.          0.          4.        ]
 [ 0.          0.33333333 -3.33333333]]
x =  [-3.875       6.13541667  0.08854167]
